spring:
  application:
    name: event-sourcing-service
  datasource:
    url: jdbc:postgresql://localhost:5432/axon
    username: axon
    password: axon
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
axon:
  serializer:
    general: jackson
